engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
      enabled: true
      
ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
   - "**.rb"
